[package]
name = "miso"
version = "0.1.0"
authors = ["Austin Tindle <tindleaj@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.11.0"
iced = "0.1.1"